---
version: "3"
services:
  apricot:
    container_name: apricot
    image: apricot
    build: .
    environment:
      BACKEND: "MicrosoftEntra"
      CLIENT_ID: "<your OpenID client ID here"
      CLIENT_SECRET: "<your OpenID client secret here>"
      DOMAIN: "<your domain here>"
      ENTRA_TENANT_ID: "<your Entra tenant ID here>"
    ports:
      - "1389:1389"
    restart: always

  redis:
    container_name: redis
    image: redis:7.2
    # command: redis-server --appendonly yes
    environment:
      REDIS_REPLICATION_MODE: master
    ports:
      - "6379:6379"
    restart: always
    volumes:
        - <local path>:/data
